build:
  maxIssues: 0

style:
  active: true
  MagicNumber:
    active: false
  WildcardImport:
    active: true
  UnusedImports:
    active: true
  ReturnCount:
    active: true
    max: 2
  MaxLineLength:
    active: false

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
  PackageNaming:
    active: false

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 30
  LongParameterList:
    active: true
    functionThreshold: 6

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false
